# Build and push new container, when a new tag gets pushed
run-name: Build & Deploy Images to GHCR

on:
  push:
    tags:
    - '*'

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and Release Image'
        run: |
          docker build . --tag ghcr.io/Rherer/resticexporter:latest
          docker push ghcr.io/Rherer/resticexporter:latest
