# Build and push new releases, when a new tag gets pushed
name: Standalone Binaries
run-name: Build Binaries
on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.24

      - name: Get dependencies
        run: go mod download

      - name: Build linux-x64 elf
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./release/restic-exporter_x64_linux

      - name: Build win-x64 exe
        run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ./release/restic-exporter_x64_win.exe

      - name: Install rpm build tools
        run: |
          sudo add-apt-repository universe
          sudo apt-get -y install rpm

      - name: Build RPM
        run: sudo rpmbuild --nodebuginfo --undefine=_disable_source_fetch --define="version ${{ github.ref_name }}" -bb restic-exporter.spec

      - name: Move rpm
        run: sudo mv /github/home/rpmbuild/RPMS/*.rpm ./release/

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./release/*
          file_glob: true
