# Build and push new releases, when a new tag gets pushed
run-name: Build Binaries
on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.24

      - name: Get dependencies
        run: go mod download

      - name: Build linux-x64 elf
        run: GOOS=linux GOARCH=amd64 go build -o ./release/restic-exporter_x64_linux

      - name: Build win-x64 exe
        run: GOOS=windows GOARCH=amd64 go build -o ./release/restic-exporter_x64_win.exe

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./release/*
          file_glob: true
